import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});
const rubikVariable = localFont({
  src: "./fonts/Rubik-VariableFont_wght.ttf",
  variable: "--font-rubik-variable",
});
export const metadata: Metadata = {
  title: "ISCIO",
  description: "Generated by create next app",
};
const major = localFont({
  src: "./fonts/MajorMonoDisplay-Regular.ttf",
  variable: "--font-major-mono",
});
const REM = localFont({
  src: "./fonts/REM-VariableFont_wght.ttf",
  variable: "--font-rem",
});

const REMitalic = localFont({
  src: "./fonts/REM-Italic-VariableFont_wght.ttf",
  variable: "--font-rem-italic",
});
const Baloo = localFont({
  src: "./fonts/Baloo2-VariableFont_wght.ttf",
  variable: "--font-baloo",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${rubikVariable.variable} ${Baloo.variable} min-h-screen flex flex-col`}
      >
        <NavBar />
        <div className="flex-grow flex flex-col">{children}</div>
      </body>
    </html>
  );
}
